### ISSUE TITLE
Crash when switching AE to OFF

### ISSUE THREAD

**Issue by michaelskyf** [KillerInk/FreeDcam#217]
**Describe the bug**
Same as in the title

**To Reproduce**
1. Select AE button in the main interface
2. Click OFF
3. Crash

Trace: 
```
FATAL EXCEPTION: main
Process: troop.com.freedcam, PID: 26439
java.lang.NumberFormatException: For input string: "1/30"
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.lang.Integer.parseInt(Integer.java:650)
	at freed.cam.apis.camera2.parameters.ae.AeManagerCamera2.setToManual(AeManagerCamera2.java:145)
	at freed.cam.apis.camera2.parameters.ae.AeManagerCamera2.setAeMode(AeManagerCamera2.java:107)
	at freed.cam.apis.camera2.parameters.ae.AeManagerCamera2$AeModeApi2.setValue(AeManagerCamera2.java:163)
	at freed.cam.apis.basecamera.parameters.AbstractParameter.setStringValue(AbstractParameter.java:193)
	at freed.cam.ui.themesample.SettingsChildAbstract.SetValue(SettingsChildAbstract.java:119)
	at freed.cam.ui.themesample.cameraui.CameraUiFragment.onCloseClicked(CameraUiFragment.java:527)
	at freed.cam.ui.themesample.cameraui.HorizontalValuesFragment.onCloseClicked(HorizontalValuesFragment.java:107)
	at freed.cam.ui.themesample.cameraui.childs.SimpleValueChild.onClick(SimpleValueChild.java:75)
	at android.view.View.performClick(View.java:7441)
	at android.view.View.performClickInternal(View.java:7418)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28677)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

**Comment by michaelskyf** [comment]
Forgot to add: I downloaded the app from FDriod
